C
C *** LAST REVISED ON 20-AUG-1994 01:20:28.15
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.LONGLIB]LL_RU.FOR
C
C	RAMTEK UTILITY ROUTINES FOR WHEN RAMTEK AVAILABLE
C
	SUBROUTINE RMWOPT(IWIND,IERR)
C
C	DGL MARCH, 1992
C
C	CHANGES CHANNEL/WINDOW ON RAMTEK DEVICE
C
C 	IWIND	DESIRED WINDOW NUMBER
C
	PARAMETER (MAXCHAN=4)		! MAXIMUM CHANNELS TO STORE
	PARAMETER (NSTORE=150)		! CHOSEN TO ENSURE THAT ISTORE
C					! IS GREATER THAN OR EQUAL TO
C					! COMMON BLOCK SIZE
	COMMON /KEEPER/ KEEP(NSTORE,MAXCHAN)
	SAVE /KEEPER/
	COMMON/RMTEK/ISTORE(NSTORE)
	SAVE /RMTEK/
C
	INTEGER XW(2), YW(2)
C
	CALL PLOTRM(0.,0.,5)
	IF (IWIND.LT.1.OR.IWIND.GT.MAXCHAN) THEN
		IERR=-1
		GOTO 99
	ENDIF
C
	ICHAN=1
	ICHTEST=IWIND
	CALL RMINFO(ICHTEST,IOPEN,IX,IY,NCOL,LCOL,XW,YW,ISIZE)
	IERR=IOPEN
	IF (IOPEN.GT.0) ICHAN=ICHTEST
	IF (ICHAN.LT.1.OR.ICHAN.GT.MAXCHAN) THEN
		IERR=-1
		GOTO 99
	ENDIF
	DO 5 I=1,NSTORE
		ISTORE(I)=KEEP(I,ICHAN)
5	CONTINUE
99	RETURN
	END
C
	SUBROUTINE RMSAVE
C
C	SAVE THE CURRENT RAMTEK CONTEXT
C
	PARAMETER (MAXCHAN=4)		! MAXIMUM CHANNELS TO STORE
	PARAMETER (NSTORE=150)		! CHOSEN TO ENSURE THAT ISTORE
C					! IS GREATER THAN OR EQUAL TO
C					! COMMON BLOCK SIZE
	COMMON /KEEPER/ KEEP(NSTORE,MAXCHAN)
	SAVE /KEEPER/
	COMMON/RMTEK/ISTORE(NSTORE)
	SAVE /RMTEK/
C
CC	INTEGER XW(2), YW(2)
C
	CALL PLOTRM(0.,0.,5)
	ICH=ISTORE(1)
	IF (ICH.LE.0) GOTO 99
CC	CALL RMINFO(ICH,IOPEN,IX,IY,NCOL,LCOL,XW,YW,ISIZE)
	IF (ICH.LT.1.OR.ICH.GT.MAXCHAN) GOTO 99
C
	DO 10 I=1,NSTORE
		KEEP(I,ICH)=ISTORE(I)
10	CONTINUE
99	RETURN
	END
C
C
	SUBROUTINE CHCHAN(ICHAN2)
C
C	FORCE CHANGE OF CHANNEL ON RAMTEK
C
	COMMON/RMTEK/ICHAN,IMR(128),RRE(2),ROX,ROY,RSF,NIMR,RANG,MM,IPW,
     $		IPSC,ICOL,RVP(4),IRID,RLIM(2),IRXLIM,IRYLIM,IDDEV
	SAVE /RMTEK/
	ICHAN=ICHAN2
	RETURN
	END
