C
C *** LAST REVISED ON 11-AUG-1994 04:47:37.53
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.DECW]RTERM.FOR
C
C ************************************************************************
C
C RAMTEK RTERM ROUTINE FOR THE LONGLIB GRAPHICS LIBRARY
C
C ************************************************************************
C
	SUBROUTINE RTERM(IX)
C
C	FORTRAN-77 VERSION:   DGL JULY, 1987
C	CLEARS RAMTEK SCREEN -- SIMILAR TO CTERM
C
C IX	CONTROL FLAG
C	= 0 CLEAR RAMTEK SCREEN
C	= 2 ASK IF RAMTEK SCREEN CLEAR
C	=-2 CLEAR RAMTEK SCREEN
C	=-4 CLEAR RAMTEK SCREEN
C	= 3 CLOSE RAMTEK CHANNEL
C	=-3 REOPEN CLOSED RAMTEK CHANNEL
C
	COMMON/RMTEK/ICHAN,IMR(128),RRE(2),ROX,ROY,RSF,NIMR,RANG,MM,IPW,
     $		IPSC,ICOL,RVP(4),IRID,RLIM(2),IRXLIM,IRYLIM,IDDEV
	SAVE /RMTEK/
C
	CHARACTER*1 ANS
	INTEGER XW(2),YW(2)
C
	IF (ICHAN.GT.0) CALL RMPAUSE(ICHAN,0)
C
	IF (ICHAN.EQ.-99.AND.IX.EQ.2) GOTO 80
	IF (ICHAN.EQ.-99.AND.IX.EQ.-3) GOTO 80
	IF (ICHAN.LE.0) RETURN
	IF (IABS(IX).GT.4) RETURN
	GOTO (10,15,10,15,10,15,20,30,15),IX+5
10	CONTINUE			! CLEAR RAMTEK SCREEN
	CALL RMCLEAR(ICHAN,IERR)
15	RETURN
20	CONTINUE
	CALL RMPAUSE(ICHAN,0)
	WRITE(*,5)			! ASK IF SCREEN CLEAR
5	FORMAT(' Clear Ramtek Screen? (y/n) [y] ',$)
	READ(*,6) ANS
6	FORMAT(A1)
	IANS=ICHAR(ANS)
	IF (IANS.GE.96) IANS=IANS-32	! MAKE UPPER CASE
	IF (IANS.EQ.89.OR.IANS.EQ.32) THEN
		GOTO 10			! CLEAR SCREEN
	ELSE
		IF (IANS.EQ.81) GOTO 30 ! TEMP. CLOSE CHANNEL
		IF (IANS.EQ.83) THEN	! DISABLE PLOTTING
CC			CALL RAMCLOSE(ICHAN)
			ICHAN=-99  		! SKIP PLOT MODE
		ENDIF
	ENDIF
	RETURN
30	CONTINUE				! TEMP. CLOSE CHANNEL
CC	CALL RAMCLOSE(ICHAN)
	ICHAN=-99
	RETURN
80	CONTINUE				! RE-ENABLE CHANNEL
CC	CALL RAMOPEN(ICHAN,IRID,IDDEV,IERR)
	CALL RMINFO(ICHAN,IOPEN,IXX,IYY,NCOL,LCOL,XW,YW,ISIZE)
	IF (ICHAN.LT.0) WRITE(*,1)
1	FORMAT(' *** ERROR *** CAN NOT REOPEN RAMTEK CHANNEL')
	RETURN
	END

