	SUBROUTINE RMREADCURSOR2(USER,ICHAN,IPNTS,JCOPT,IHIGH,
     $		IX1,IY1,IX2,IY2,IC)
	EXTERNAL USER
        DIMENSION IPNTS(1)
	CALL RMREADCURSOR2_(USER,ICHAN,IPNTS,JCOPT,IHIGH,
     $		IX1,IY1,IX2,IY2,IC)
	RETURN
	END
