C
C *** LAST REVISED ON  8-DEC-1993 07:38:16.64
C *** SOURCE FILE: [LONGD.TEMP]COLORTABLE.FOR
C
	SUBROUTINE COLORTABLE(ICHAN,NCOL)
	CHARACTER*80 CNAME
C
C	READS A COLOR TABLE FROM A FILE AND DOWN LOADS TO THE RAMTEK
C	DEVICE.  RETURNS THE NUMBER OF AVAILABLE COLORS IN NCOL
C
	IF (ICHAN.LE.0) RETURN
C
10	WRITE (*,44)
44	FORMAT(' Color table file: (BLANK=NONE) ',$)
	READ (*,15) CNAME
15	FORMAT(A80)
C
	IF (ICHAN.NE.99999) THEN
		 IF (NCOL.GT.256) NCOL=255
		 IF (CNAME.NE.' ') THEN
		  I=-1
		  OPEN(2,ERR=99,FILE=CNAME,STATUS='OLD',FORM='FORMATTED')
C     1		  ,READONLY)
		  I=0
		  READ(2,'(I4)',ERR=98) NCOL1
		  WRITE (*,*) 'Number of color table entries:',NCOL1
		  DO I=1,NCOL1
			READ(2,'(3I4)',ERR=98) IRED,IGREEN,IBLUE
			IRED=IRED*128
			IGREEN=IGREEN*128
			IBLUE=IBLUE*128
			IF (I.LE.NCOL) THEN
				CALL RMWRCOLIND(ICHAN,IRED,IGREEN,
     $						IBLUE,I,IERR)
			ENDIF
		  END DO
		  CLOSE(2)
		 ENDIF
	ENDIF
	RETURN
98	WRITE (*,*) '*** READ ERROR ***'
99	WRITE (*,*) '*** COLOR TABLE FILE ERROR ***'
	WRITE (*,*) '"',CNAME,'"',I
	GOTO 10
	END



