C
C *** LAST REVISED ON  9-DEC-1993 23:24:45.51
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.COLOR]EDITCOLORTABLE.FOR
C
	SUBROUTINE EDITCOLORTABLE(ICHAN,NCOL)
	CHARACTER*80 CNAME
	IF (ICHAN.LE.0) RETURN
	IF (ICHAN.EQ.99999) RETURN
C
	WRITE (*,*) 'Edit color table. Max Number of Colors:',NCOL
	INDEX=0
10	CONTINUE
	CALL RMPAUSE(ICHAN,0)
	WRITE (*,44)
44	FORMAT(' Index Number: (-1=SAVE TABLE, ^Z OR 0=EXIT EDIT) ',$)
	INDEX=IREADVAL1(INDEX+1,IEND)
	IF (INDEX.EQ.-1) THEN
		WRITE (*,55)
55		FORMAT(' Enter output file name: ',$)
		READ (*,56) CNAME
56		FORMAT(A80)
		OPEN(2,FILE=CNAME,STATUS='NEW',FORM='FORMATTED')
		WRITE (2,'(I4)') NCOL
		DO I=1,NCOL
		  CALL RMRDCOLIND(ICHAN,IRED,IGREEN,IBLUE,I,IERR)
		  IRED=IRED/128
		  IGREEN=IGREEN/128
		  IBLUE=IBLUE/128
		  WRITE (2,'(3I4)') IRED,IGREEN,IBLUE
		END DO
		CLOSE(2)
		CALL RMPAUSE(ICHAN,0)
	ENDIF
	IF (IEND.LT.0.OR.INDEX.LE.0) RETURN
	INDEX=MIN(INDEX,NCOL)
C
	CALL RMRDCOLIND(ICHAN,IRED,IGREEN,IBLUE,INDEX,IERR)
	IRED=IRED/128
	IGREEN=IGREEN/128
	IBLUE=IBLUE/128
	WRITE (*,100) INDEX,IRED,IGREEN,IBLUE
100	FORMAT(' Index->',I4,'  R:',I3,'  G:',I3,'  B:',I3)
C
	CALL RMPAUSE(ICHAN,0)
	WRITE (*,45) 'Red  ',IRED
45	FORMAT(1X,A5,' Value: [',I3,']: ',$)
	IRED=MIN(NCOL,MAX(IREADVAL(IRED,IEND),0))
	IF (IEND.LT.0) GOTO 50
	CALL RMPAUSE(ICHAN,0)
	WRITE (*,45) 'Green',IGREEN
	IGREEN=MIN(NCOL,MAX(IREADVAL(IGREEN,IEND),0))
	IF (IEND.LT.0) GOTO 50
	CALL RMPAUSE(ICHAN,0)
	WRITE (*,45) 'Blue ',IBLUE
	IBLUE=MIN(NCOL,MAX(IREADVAL(IBLUE,IEND),0))
	IF (IEND.LT.0) GOTO 50
C
50	CONTINUE
	IRED=IRED*128
	IGREEN=IGREEN*128
	IBLUE=IBLUE*128
	CALL RMWRCOLIND(ICHAN,IRED,IGREEN,IBLUE,INDEX,IERR)
	GOTO 10
	END
