C
C
	SUBROUTINE ARROW(X,Y,ALEN,ANG,APT,APTAN)
C
C	CREATED BY D. LONG, DEC. 1983 AT JPL
C	PLOTS AN ARROW WITH CHOICE OF HEADS
C
C	X,Y	(R)	LOCATION OF TAIL (INCHES)
C	ALEN	(R)	LENGTH OF ARROW (INCHES)
C	ANG	(R)	ANGLE FROM HORIZONTAL (DEGREES)
C	APT	(R)	LENGTH OF ARROW POINT (INCHES)
C			> 0   -->  (NORMAL ARROW)
C			< 0   -I> (DELTA HEAD ARROW)
C	APTAN	(R)	ANGLE OF ARROW POINT FROM LINE (DEGREES)
C
	DATA API/0.0174532/		! PI/180
	IF (ALEN.EQ.0.0) RETURN
	X0=X+ALEN*COS(API*ANG)
	Y0=Y+ALEN*SIN(API*ANG)
	CALL PLOT(X,Y,3)
	CALL PLOT(X0,Y0,2)
	X1=X0+ABS(APT)*COS(API*(180.-APTAN+ANG))
	Y1=Y0+ABS(APT)*SIN(API*(180.-APTAN+ANG))
	CALL PLOT(X1,Y1,2)
	IF (APT.GT.0.0) CALL PLOT(X0,Y0,2)
	X1=X0+ABS(APT)*COS(API*(APTAN+ANG-180.))
	Y1=Y0+ABS(APT)*SIN(API*(APTAN+ANG-180.))
	CALL PLOT(X1,Y1,2)
	IF (APT.LT.0.0) CALL PLOT(X0,Y0,2)
	CALL PLOT(X,Y,3)
	RETURN
	END
