C
	SUBROUTINE CIRCLE(X,Y,A1,A2,R1,R2,D)
C
C	CREATED BY D. LONG    AUG, 1983		AT JPL
C
C	THIS ROUTINE PLOTS A CIRCLE USING THE PLOTTING RESOLUTION
C	AND CIRCLE SIZE TO MAKE A GOOD "APPERANCE" OF A CONTINUOUS CIRCLE.
C
C	X,Y	(R) LOCATION OF CIRCLE CENTER
C	A1	(R) ANGLE OF STARTING POINT FROM HORIZONTAL IN DEGREES
C	A2	(R) ANGLE TO ENDING POINT IN DEGREES
C	R1	(R) RADIUS OF STARTING POINT
C	R2	(R) RADIUS OF ENDING POINT
C	D	(R) D=0.0	SOLID (CONNECTED) LINE
C		    D=0.5	DASHED LINE (SOFTWARE GENERATED)
C
	LOGICAL FLAG,PEN
	FLAG=.TRUE.
	TPI=3.141592654/180.0
	SIZE=.1 			! CIRCLE RESOLUTION
	DASHL=.3			! DASH LINE DASH SIZE
	SPACE=DASHL/2.1 		! DASH LINE SPACE SIZE
	A=A1
	R=R1
	ARG=A*TPI
	X1=R*COS(ARG)+X
	Y1=R*SIN(ARG)+Y
	X2=X1
	Y2=Y1
	CALL PLOT(X1,Y1,3)		! PLOT START POINT
	PEN=.TRUE.
	IPEN=2
	DIS=0.
	IF (A1.EQ.A2.OR.R1.LT.0..OR.R2.LT.0.) RETURN
	RD=(R2-R1)/(A2-A1)
100	ARG=A*TPI
	IF (ABS(ACOS(SIZE/R)).LT.ABS(ASIN(SIZE/R))) THEN ! COMPUTE ANGLE INCREM.
		AI=ABS(ACOS(SIZE/R)/TPI)+.01		! BASED ON RESOLUTION
	ELSE						! OF CIRCLE
		AI=ABS(ASIN(SIZE/R)/TPI)+.01
	ENDIF
	A=A+AI*SIGN(1.,A2-A1)
	IF (ABS(A-A2).LT.AI+.01) THEN
		IF (FLAG) THEN				! FINISH LAST POINT
			A=A2
			FLAG=.FALSE.
			IPEN=2
			GOTO 110
		ENDIF
		CALL PLOT(X,Y,3)			! END CURVE
		RETURN
	ENDIF
110	R=R1+RD*(A-A1)
	ARG=A*TPI
	X1=R*COS(ARG)+X
	Y1=R*SIN(ARG)+Y
	CALL PLOT(X1,Y1,IPEN)
	IF (D.EQ.0.5) THEN				! DASHED CURVE
		DIS=SQRT((X1-X2)**2+(Y1-Y2)**2)+DIS
		IF (DIS.GT.DASHL.AND.PEN) THEN
			PEN=.FALSE.
			IPEN=3
			DIS=0.
			GOTO 120
		ENDIF
		IF (DIS.GT.SPACE.AND..NOT.PEN) THEN
			PEN=.TRUE.
			IPEN=2
			DIS=0.
		ENDIF
120		X2=X1
		Y2=Y1
	ENDIF
	GOTO 100
	END
