C
C
	SUBROUTINE ELLIPSE(X0,Y0,SMAJ,SMIN,ANG,AST,AEND)
C
C	WRITTEN BY:	DG LONG,  JPL  JUNE 1985
C	MODIFIED: DGL NOV 7,1985 TO HANDLE DEGENERATE ELLIPSES
C
C	THIS ROUTINE PLOTS AN ELLIPSE.  THE NUMBER OF LINE SEGMENTS
C	USED TO PLOT THE CURVE IS DEPENDENT ON THE RADIUS OF THE ELLIPSE
C	AT EACH POINT.
C
C	X0,Y0	(R)	CENTER OF ELLIPSE (HALFWAY BETWEEN FOCI)
C	SMAJ	(R)	LENGTH OF SEMI-MAJOR AXIS (DISTANCE FROM ELLIPSE
C				CENTER TO CURVE THROUGH ONE FOCUS)
C	SMIN	(R)	LENGTH OF SEMI-MINOR AXIS (PERPENDICULAR TO SMAJ)
C				0 < SMIN < SMAJ
C	ANG	(R)	ANGLE FROM HORIZONTAL OF SEMI-MAJOR AXIS (DEG)
C	AST	(R)	START ANGLE OF ELLIPSE CURVE FROM SEMI-MAJOR AXIS (DEG)
C	AEND	(R)	END ANGLE OF ELLIPSE CURVE FROM SEMI-MAJOR AXIS (DEG)
C				AEND > AST
C
C	AST AND AEND ARE DEFINED USING THE IDENTITY FOR AN ELLIPSE:
C		(X,Y) = (SMAJ * COS(T) , SMIN * SIN(T) )
C
	DATA ERR/0.025/		! WORST-CASE PLOTTING ERROR
C
	IP=3
	RANG=ANG*3.141592654/180.
	CO=COS(RANG)
	SI=SIN(RANG)
	DTHETA=ASIN(ERR/SMAJ)
	TANG=AST*3.141592654/180.
	EANG=AEND*3.141592654/180.
C
100	CONTINUE
		X=COS(TANG)*SMAJ
		Y=SIN(TANG)*SMIN
		X1=CO*X-SI*Y+X0
		Y1=SI*X+CO*Y+Y0
		CALL PLOT(X1,Y1,IP)
		IP=2
		R=SQRT(X**2+Y**2)
		AA=2.
		IF (R.GT.0.0) AA=ERR/R
		IF (ABS(AA).LT.1.0) THEN
			AA=ASIN(AA)
		ELSE
			AA=0
		ENDIF
		DTHETA=MAX(AA,0.00001)	! MINIMUM STEP SIZE
		TANG=TANG+DTHETA
		IF (TANG.GT.EANG) GOTO 200
	GOTO 100
C
200	CONTINUE
	X=COS(EANG)*SMAJ
	Y=SIN(EANG)*SMIN
	X1=CO*X-SI*Y+X0
	Y1=SI*X+CO*Y+Y0
	CALL PLOT(X1,Y1,2)
	CALL PLOT(X0,Y0,3)	! LEAVE PEN AT ELLIPSE CENTER
C
	RETURN
	END
