C
C
	SUBROUTINE GRID(X,Y,DX,DY,NX,NY)
C
C	ROUTINE TO PRODUCE CARTESIAN GRID
C
C	CREATED BY D. LONG    AUG, 1983	AT JPL
C
C	X,Y	CORRDINATES OF BOTTOM LEFT CORNER
C	DX,DY	SPACING OF GRID LINES IN X AND Y DIRECTIONS
C	NX,NY	NUMBER OF GRIDS IN X AND Y DIRECTIONS
C		IF NY > 0 AND NX > 0 THEN SOLID GRID DRAWN
C		IF NY < 0 OR NX < 0  TICK MARKS USED
C		IF NY < 0 AND NX < 0 THEN GRID AREA IS BOXED
C
	IF (NX.LT.0.OR.NY.LT.0) GOTO 200
	IF (NX.EQ.0.OR.NY.EQ.0) RETURN
	CALL PLOT(X,Y,3)			! SOLID GRID
	DO 100 IX=0,NX
		X1=X+IX*DX
		X2=X+(IX+1)*DX
		Y1=Y+NY*DY
		CALL PLOT(X1,Y1,2)
		CALL PLOT(X2,Y,3)
 100	CONTINUE
	CALL PLOT(X,Y,3)
	DO 150 IY=0,NY
		Y1=Y+IY*DY
		Y2=Y+(IY+1)*DY
		X1=X+NX*DX
		CALL PLOT(X1,Y1,2)
		CALL PLOT(X,Y2,3)
 150	CONTINUE
	CALL PLOT(X,Y,3)
	RETURN
 200	NX1=IABS(NX)				! TICKED GRID
	NY1=IABS(NY)
	EX=X+FLOAT(NX1)*DX
	EY=Y+FLOAT(NY1)*DY
	IF (ISIGN(1,NX).EQ.ISIGN(1,NY)) THEN	! BOX GRID AREA
		CALL PLOT(X,Y,3)
		CALL PLOT(EX,Y,2)
		CALL PLOT(EX,EY,2)
		CALL PLOT(X,EY,2)
		CALL PLOT(X,Y,2)
	ENDIF
	T=.05					! TICK SIZE
	DO 300 IX=0,NX1
		DO 300 IY=0,NY1
			X0=X+FLOAT(IX)*DX
			Y0=Y+FLOAT(IY)*DY
			X1=X0+T
			X2=X0-T
			Y1=Y0+T
			Y2=Y0-T
			IF (X2.LT.X)  X2=X
			IF (X1.GT.EX) X1=EX
			IF (Y2.LT.Y)  Y2=Y
			IF (Y1.GT.EY) Y1=EY
			CALL PLOT(X1,Y0,3)
			CALL PLOT(X2,Y0,2)
			CALL PLOT(X0,Y1,3)
			CALL PLOT(X0,Y2,2)
300	CONTINUE
	RETURN
	END
