C
	SUBROUTINE LGLIN(X,Y,N,K,J,L,LG,IX,IY,XMIN,DX,YMIN,DY)
C
C	PLOTS A LOGRITHMIC LINE
C	D.LONG 8-AUG-1983	AT JPL
C
C	X	(R) ARRAY OF ABCISSA VALUES
C	Y	(R) ARRAY OF ORDINATE VALUES
C	N	(I) NUMBER OF POINTS IN THE ARRAY
C	K	(I) REPEAT CYCLE OF A MIXED ARRAY (NORMALLY =1)
C	J	(I) >0, SYMBOL AND LINE.  SYMBOLS PLOTTED EVERY JTH POINT
C		    =0, LINE ONLY
C		    <0, SYMBOL ONLY. SYMBOLS PLOTTED EVERY JTH POINT
C	L	(I) NUMBER OF SYMBOL
C	LG	(I) = -2 : X AND Y ARE LOGARITHMIC
C		    = -1 : X IS LOGARITHMIC, Y IS LINEAR
C		    =  1 : X IS LINEAR, Y IS LOGARITHMIC
C	IX,IY	(I) FIRST REVALENT VALUE IN X,Y ARRAY
C	XMIN,YMIN (R) MINIMUM VALUES IN ARRAY (DETERMINED BY SCALG)
C	DX,DY	(R) SCALED (SMOOTHED) INCREMENT (DETERMINED BY SCALG)
C
C	NOTE: IF LOG OF ZERO IS GOING TO OCCUR 1.E-38 IS SUBSTITUTED.
C	      ABSOLUTE VALUE OF X,Y ARRAYS ARE USED WHEN LOG IS COMPUTED.
C
	REAL X(1),Y(1)
	IF (N.LT.1) GOTO 110
	LA=L
	IF (LA.LT.0.OR.LA.GT.117) LA=100
	I2=1
	I3=3
	IF (J.GE.0) I3=2
	I4=3
	I5=N
100	XI=X(I2)
	YI=Y(I2)
	IF (LG.EQ.1) GOTO 101
	IF (XI.EQ.0.0) XI=1.E-38
	XI=ALOG10(ABS(XI))
101	IF (LG.EQ.-1) GOTO 102
	IF (YI.EQ.0.0) YI=1.E-38
	YI=ALOG10(ABS(YI))
102	IF (DX.NE.0.0) THEN
		X1=(XI-XMIN)/DX
	ELSE
		X1=0.0
	ENDIF
	IF (DY.NE.0.0) THEN
		Y1=(YI-YMIN)/DY
	ELSE
		Y1=0.0
	ENDIF
	CALL PLOT(X1,Y1,I4)
	I4=I3
	IF (J.NE.0) THEN
		IF (MOD((I2-IX),J*K).EQ.0) CALL
     $			SYMBOL(X1,Y1,0.14,CHAR(LA),0.0,-1,-1)
	ENDIF
	I2=I2+K
	I5=I5-1
	IF (I5.GT.0) GOTO 100
110	RETURN
	END
