C
C
	SUBROUTINE LGRID(X,Y,DX,DY,NX,NY,IF)
C
C	ROUTINE TO PRODUCE LOGRITHMIC GRID
C
C	CREATED BY D. LONG    NOV, 1983		AT JPL
C
C	X,Y	COORDINATES OF BOTTOM LEFT CORNER
C	DX,DY	SPACING OF GRID LINES IN X AND Y DIRECTIONS
C	NX,NY	NUMBER OF GRIDS IN X AND Y DIRECTIONS
C		IF NY > 0 AND NX > 0 THEN LINEAR GRID
C		IF NY < 0 AND NX < 0 THEN LOG X AND LINEAR Y
C		IF NY < 0 AND NX < 0 THEN LOG X AND LOG Y
C		IF NY > 0 AND NX > 0 THEN LINEAR Y AND LOG Y
C	IF	OPTION FLAG
C		= 0 SOLID.  MINOR LINES FOR LOG SPACING
C		= 1 DOTTED. MINOR LINES FOR LOG SPACING
C		= 2 SOLID.  MINOR TICKS FOR LOG SPACING
C
	IF (NX.EQ.0.OR.NY.EQ.0) RETURN
	IF (IF.EQ.1) CALL NEWPEN(2)		! DOTTED LINES
	XM=IABS(NX)*DX+X
	YM=IABS(NY)*DY+Y
	INX1=IABS(NX)+1
	INY1=IABS(NY)+1
	CALL PLOT(X,Y,3)
	CALL PLOT(X,YM,2)
	DO 100 IX=1,IABS(NX)
		IF (NX.LT.0) THEN
			X0=(IX-1)*DX+X
			DO 50 IXM=2,9
			    X1=ALOG10(FLOAT(IXM))*DX+X0
			    IF (IF.GE.2) THEN
				 DO 30 IY=1,INY1
				    Y0=(IY-1)*DY+Y-.08
				    Y1=Y0+.16
				    IF (IY.EQ.1.AND.DY.GT.0.0) Y0=Y
				    IF (IY.EQ.1.AND.DY.LT.0.0) Y1=Y
				    IF (IY.EQ.INY1.AND.DY.GT.0.0) Y1=YM
				    IF (IY.EQ.INY1.AND.DY.LT.0.0) Y0=YM
				    CALL PLOT(X1,Y0,3)
				    CALL PLOT(X1,Y1,2)
30				CONTINUE
			    ELSE
				CALL PLOT(X1,Y,3)
				CALL PLOT(X1,YM,2)
			    ENDIF
50			CONTINUE
		ENDIF
	X0=IX*DX+X
	CALL PLOT(X0,Y,3)
	CALL PLOT(X0,YM,2)
100	CONTINUE
	CALL PLOT(X,Y,3)
	CALL PLOT(XM,Y,2)
	DO 200 IY=1,IABS(NY)
		IF (NY.LT.0) THEN
			Y0=(IY-1)*DY+Y
			DO 150 IYM=2,9
			    Y1=ALOG10(FLOAT(IYM))*DY+Y0
			    IF (IF.GE.2) THEN
				 DO 130 IX=1,INX1
				    X0=(IX-1)*DX+X-.08
				    X1=X0+.16
				    IF (IX.EQ.1.AND.DX.GT.0.0) X0=X
				    IF (IX.EQ.1.AND.DX.LT.0.0) X1=X
				    IF (IX.EQ.INX1.AND.DX.GT.0.0) X1=XM
				    IF (IX.EQ.INX1.AND.DX.LT.0.0) X0=XM
				    CALL PLOT(X0,Y1,3)
				    CALL PLOT(X1,Y1,2)
130				 CONTINUE
			    ELSE
				 CALL PLOT(X,Y1,3)
				 CALL PLOT(XM,Y1,2)
			    ENDIF
150			CONTINUE
		ENDIF
	Y0=IY*DY+Y
	CALL PLOT(X,Y0,3)
	CALL PLOT(XM,Y0,2)
200	CONTINUE
	IF (IF.EQ.1) CALL NEWPEN(1)		! SOLID LINES
	RETURN
	END
