C
C *** LAST REVISED ON  4-JAN-1994 10:07:45.88
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.AUXLIB]LINE2.FOR
C
	SUBROUTINE LINE2(X,Y,N,K,J,L,IX,IY,XMIN,DX,YMIN,DY,DDX)
C
C	THIS VERSION, WHEN CONNECTING POINTS PUTS GAPS WHEN
C	DISTANCE BETWEEN X VALUES EXCEEDS DDX
C
C	X	(R) ARRAY OF UNSCALED ABCISSA VALUES
C	Y	(R) ARRAY OF UNSCALED ORDINATE VALUES
C	N	(I) NUMBER OF POINTS IN THE ARRAY
C	K	(I) REPEAT CYCLE OF A MIXED ARRAY (NORMALLY =1)
C	J	(I) >0, SYMBOL AND LINE SYMBOL EVERY JTH POINT
C		    =0, LINE ONLY
C		    <0, SYMBOL ONLY SYMBOL EVERY JTH POINT
C	L	(I) NUMBER OF SYMBOL ,SEE SYMBOL ROUTINE FOR LIST
C	IX,IY	(I) FIRST REVALENT VALUE IN X,Y ARRAY
C	XMIN,YMIN (R) MINIMUM VALUES IN ARRAY (DETERMINED BY SCALE)
C	DX,DY	(R) SCALED SMOOTHED INCREMENTS (DETERMINED BY SCALE)
C		    IF DX=0.0, THE PLOTTED X IS ZERO
C		    IF DY=0.0, THE PLOTTED Y IS ZERO
C	DDX	(R) CONTINUITY IN POINTS ONLY IF SEPARATION IN X VALUES
C			IS LESS THAN DDX
C
C	XPLOTTED=(X(I)-XMIN)/DX
C	YPLOTTED=(Y(I)-YMIN)/DY
C
	REAL X(1),Y(1)
	LOGICAL TOGETHER
	save TOGETHER
	data TOGETHER/.false./
	IF (N.LT.1) RETURN
	JA=IABS(J)
	NC=-1
	IF (J.GT.0) NC=-2
	LA=L
	IF (LA.LT.0.OR.LA.GT.117) LA=100
	I2=1
	I3=3
	IF (J.GE.0) I3=2
	I4=3
	I5=N
	XLAST=X(1)
100	IF (DX.NE.0.0) THEN
		X1=(X(I2)-XMIN)/DX
		IF (ABS(X(I2)-XLAST).GT.DDX.AND.DDX.GT.0.0) THEN
			TOGETHER=.FALSE.
		ELSE
			TOGETHER=.TRUE.
		ENDIF
		XLAST=X(I2)
	ELSE
		X1=0.0
	ENDIF
	IF (DY.NE.0.0) THEN
		Y1=(Y(I2)-YMIN)/DY
	ELSE
		Y1=0.0
	ENDIF
	IF (TOGETHER) CALL PLOT(X1,Y1,I4)
	I4=I3
	IF (J.NE.0) THEN
		IF(MOD(I2-1,JA).EQ.0) CALL 
     $			SYMBOL(X1,Y1,0.14,CHAR(LA),0.0,NC,-1)
	ELSE
		IF (TOGETHER) THEN
			CALL PLOT(X1,Y1,I4)
		ELSE
			CALL PLOT(X1,Y1-0.005,3)
			CALL PLOT(X1,Y1,I4)
		ENDIF
	ENDIF
	I2=I2+K
	I5=I5-1
	IF (I5.GT.0) GOTO 100
	RETURN
	END
