C
C
	SUBROUTINE NXT0VU(X,Y,W,KK,LL,IER)
	SAVE
C
C	ROUTINE TO STORE NEW DATA IN SURFACE HISTORY ARRAY IN NXTVU
C	MODIFIED 8/11/87 BY D.LONG, JPL
C
	DIMENSION W(1)
	DATA EPS/0.001/		! ZERO TEST VALUE
	IF (KK.EQ.0) GOTO 10
	IF (2*KK.GE.LL-1) GOTO 20
	IF (ABS(W((KK-1)*2+1)-X)+ABS(W(2*KK)-Y).LT.EPS) RETURN
10	KK=KK+1
	W((KK-1)*2+1)=X
	W(2*KK)=Y
	RETURN
20	IER=1
	RETURN
	END
