C
C
	SUBROUTINE PLT3D(A,MD,ND,M,N,D,L,W2,NN,ALT,AZ,XLEN,XOFF,
     $		YLEN,YOFF,ZFAC,ZOFF,IER)
	SAVE
C
C	ROUTINE TO PLOT A GRID SCRIBED ON A 3D SURFACE USING NXTVU
C	TO PROVIDE HIDDEN LINE REMOVAL
C	MODIFIED 8/11/87 BY D.LONG, JPL
C
C	A	(R): MD BY ND ARRAY CONTAINING Z VALUES TO BE PLOTTED
C	MD,ND	(I): DIMENSIONS OF A
C	M,N	(I): SIZE OF DATA IN A ARRAY  M,N > 1
C	D	(R): WORKING ARRAY OF DIMENSIONED D(L)
C	L	(I): DIMENSION OF D ARRAY
C	W2	(R): WORKING ARRAY OF DIMENSIONED W2(NN)
C	NN	(I): DIMENSION OF W2 ARRAY
C	ALT,AZ	(R): VIEWING ALTITUDE, AZIMUTH IN DEGREES
C	XLEN	(R): LENGTH OF UNPROJECTED X AXIS IN INCHES
C			> 0 SURFACE ABOVE PLANE SHOWN
C			< 0 SURFACE BELOW PLANE SHOWN
C	XOFF	(R): ORIGIN OF PLOT
C	YLEN	(R): LENGTH OF UNPROJECTED Y AXIS IN INCHES
C	YOFF	(R): ORIGIN OF PLOT
C	ZFAC	(R): Z COORDINATE SCALE FACTOR (Zplotted=ZFAC*A(I,J)+ZOFF)
C	ZOFF	(R): Z AXIS OFFSET VALUE
C	IER	(I): RETURNED ERROR CODE
C			0: NO ERROR
C			1: WORKING STORAGE W2 INTERNAL SPACE EXCEEDED
C			2: L LESS THAN 2*MIN(M,N)
C
	DIMENSION D(L),A(MD,ND),W2(NN)
C
	COMMON /PLT3B/A1,A2,A3,B1,B2,B3,B4
cc	SAVE /PLT3B/
	DATA DTR/0.0174532925/
C
	IX(I)=(I-1)*2+1
	IY(I)=I*2
C
	LMAX=2*MIN(M,N)
	IF (L.LT.2*LMAX) GOTO 500
	TAZ=AZ*DTR
	TALT=ALT*DTR
	SAZ=SIN(TAZ)
	CAZ=COS(TAZ)
	SAL=SIN(TALT)
	CAL=COS(TALT)
	XSC=ABS(XLEN)/FLOAT(N-1)
	ID=1
	IF (XLEN.LT.0.0) ID=-1
	YSC=YLEN/FLOAT(M-1)
	A1=CAZ*XSC
	A2=-SAZ*YSC
	A3=XOFF-0.5*(A1*FLOAT(N+1)+A2*FLOAT(M+1))
	B1=SAZ*SAL*XSC
	B2=CAZ*SAL*YSC
	B3=ZFAC*CAL
	B4=B3*ZOFF+YOFF-0.5*(B1*FLOAT(N+1)+B2*FLOAT(M+1))
	IAZ=1
	IF (A1.LE.0.0) IAZ=IAZ+1
	IF (A2.LE.0.0) IAZ=IAZ+2
	GOTO (10,20,10,20), IAZ
10	IFIRST=1
	ISTEP=1
	ILAST=M
	GOTO 30
20	IFIRST=M
	ISTEP=-1
	ILAST=1
30	GOTO (50,50,40,40),IAZ
40	JFIRST=1
	JSTEP=1
	JLAST=N
	GOTO 60
50	JFIRST=N
	JSTEP=-1
	JLAST=1
60	GOTO (64,62,62,64),IAZ
62	LLI=1
	GOTO 66
64	LLI=-1
66	IC=ID
	IBEG=IFIRST+ISTEP
70	LNTH=MIN(2*IABS(IBEG-IFIRST)+1,LMAX)
	IF (LLI.EQ.-1) GOTO 72
	LL=0
	GOTO 74
72	LL=LNTH+1
74	I=IBEG
	J=JFIRST
	XX=FLOAT(J)
	YY=FLOAT(I)
	LL=LL+LLI
	D(IX(LL))=A1*XX+A2*YY+A3
	D(IY(LL))=B1*XX+B2*YY+B3*(A(I,J)+ZOFF)+B4
80	I=I-ISTEP
	YY=FLOAT(I)
	LL=LL+LLI
	D(IX(LL))=A1*XX+A2*YY+A3
	D(IY(LL))=B1*XX+B2*YY+B3*(A(I,J)+ZOFF)+B4
	IF (J.EQ.JLAST) GOTO 85
	J=J+JSTEP
	XX=FLOAT(J)
	LL=LL+LLI
	D(IX(LL))=A1*XX+A2*YY+A3
	D(IY(LL))=B1*XX+B2*YY+B3*(A(I,J)+ZOFF)+B4
	IF (I.NE.IFIRST) GOTO 80
85	CALL NXTVU(IC,D,LNTH,W2,NN,IER)
	IF (IER.NE.0) RETURN
	IC=2*ID
	IF (IBEG.EQ.ILAST) GOTO 90
	IBEG=IBEG+ISTEP
	GOTO 70
90	JBEG=JFIRST
100	LNTH=MIN(2*IABS(JBEG-JLAST)+1,LMAX)
	IF (LLI.EQ.-1) GOTO 102
	LL=0
	GOTO 104
102	LL=LNTH+1
104	I=ILAST
	J=JBEG
	XX=FLOAT(J)
	YY=FLOAT(I)
	LL=LL+LLI
	D(IX(LL))=A1*XX+A2*YY+A3
	D(IY(LL))=B1*XX+B2*YY+B3*(A(I,J)+ZOFF)+B4
110	J=J+JSTEP
	XX=FLOAT(J)
	LL=LL+LLI
	D(IX(LL))=A1*XX+A2*YY+A3
	D(IY(LL))=B1*XX+B2*YY+B3*(A(I,J)+ZOFF)+B4
	IF (I.EQ.IFIRST) GOTO 120
	I=I-ISTEP
	YY=FLOAT(I)
	LL=LL+LLI
	D(IX(LL))=A1*XX+A2*YY+A3
	D(IY(LL))=B1*XX+B2*YY+B3*(A(I,J)+ZOFF)+B4
	IF (J.NE.JLAST) GOTO 110
120	CALL NXTVU(ID*2,D,LNTH,W2,NN,IER)
	IF (IER.NE.0) RETURN
	JBEG=JBEG+JSTEP
	IF (JBEG.EQ.JLAST) RETURN
	GOTO 100
500	IER=2
	RETURN
	END
