C
C
	SUBROUTINE SCALG(X,S,N,K,IX,XMIN,DX)
C
C	COMPUTES SCALE FACTORS FOR INPUT DATA USING LOG SCALING
C	MODIFIED FROM SCALE D.LONG 4-AUG-83	AT JPL
C
C	X	ARRAY OF DATA TO BE SCANNED FOR MAXIMUM AND MINIMUM
C		VALUES.
C	S	LENGTH OVER WHICH THIS DATA IS TO BE PLOTTED.
C	N	NUMBER OF DATA POINTS IN THE ARRAY X.
C	K	REPEAT CYCLE OF MIXED ARRAY(NORMALLY 1).
C	IX	FIRST RELEVANT DATA POINT IN X
C	XMIN	SMOOTHED MINIMUM AFTER CALL
C	DX	SMOOTHED INCREMENT AFTER CALL
C
C	NOTE: IF X(I)=0.0 THEN 1.E-38 IS USED INSTEAD.
C	      ABSOLUTE VALUE OF X ARRAY IS USED.
C
	REAL X(1)
	NP=N*K
	XI=ABS(X(1))
	IF (XI.EQ.0.0) XI=1.E-38
	XMAX=ALOG10(XI)
	XMIN=XMAX
	DO 100 I=1,NP,K
		XI=ABS(X(I))
		IF (XI.EQ.0.0) XI=1.E-38
		XI=ALOG10(XI)
		XMAX=AMAX1(XMAX,XI)
		XMIN=AMIN1(XMIN,XI)
100	CONTINUE
	SJ=AINT(XMIN)
	IF (XMIN.LT.SJ) SJ=SJ-1.
	SJ2=ANINT(XMAX+.5)
	DX=(SJ2-SJ)/S
	XMIN=SJ
	RETURN
	END
