C
C *** LAST REVISED ON  8-DEC-1993 07:25:30.44
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.MASTER]CVAX3D.FOR
C
	SUBROUTINE CVAX3D(A,INX,INZ,NX,NZ,ALPHA,BETA,XH,YH,ZH,IFLAG,
     $		IAXIS,CLOW,NLEV,CVAL,NCH,NMIN,ILINE,IPLS,
     $		XT,NXT,XASTART,XAEND,YT,NYT,ZT,NZT,ZASTART,ZAEND,
     $		AMININ,AMAXIN,ICOL)
C
C	CREATED BY D. LONG  AUG 1987	AT JPL
C
C	SIMPLIFIES CALLING CVAX3DX ROUTINE
C
	DIMENSION A(INX,INZ),ICOL(1),ILINE(1),CVAL(1),IPLS(1)
	CHARACTER*(*) XT,YT,ZT
	IAX=MOD(IAXIS,100)
	IF (IAXIS.LT.0) THEN
		AMN=AMININ
		AMX=AMAXIN
	ENDIF
	IF (MOD(IABS(IFLAG),10).EQ.2) THEN
		CALL CVAX3DX(A,INX,INZ,NX,NZ,ALPHA,BETA,XH,YH,ZH,IFLAG,
     $		        IAX,CLOW,NLEV,CVAL,NCH,NMIN,ILINE,IPLS,
     $			XT,NXT,XASTART,XAEND,TX,TSX,FDX,
     $			YT,NYT,TY,TSY,FDY,
     $			ZT,NZT,ZASTART,ZAEND,TZ,TSZ,FDZ,
     $			AMN,AMX,ICOL)
	ELSE
		CALL CVAX3DX(A,INX,INZ,NX,NZ,ALPHA,BETA,XH,YH,ZH,IFLAG,
     $		        IAX,CLOW,NLEV,CVAL,NCH,NMIN,ILINE,IPLS,
     $			XT,NXT,XASTART,XAEND,TX,TSX,FDX,
     $			YT,NYT,TY,TSY,FDY,
     $			ZT,NZT,ZASTART,ZAEND,TZ,TSZ,FDZ,
     $			AMN,AMX,IC)
	ENDIF
	RETURN
	END
