C
C *** LAST REVISED ON  8-DEC-1993 07:03:25.89
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.MASTER]MLIB.FOR
C
	SUBROUTINE INTERSECT(FLAG,X,Y,AX1,AY1,AX2,AY2,BX1,BY1,BX2,BY2,A)
C
C	CREATED BY D. LONG     AUG, 1983	AT JPL
C	SUBPROGRAM OF VAX3DX
C
C	DETERMINE IF TWO SEGMENTS INTERSECT AND THE POINT OF INTERSECTION
C	IF STARTING POINTS OF SEGMENTS ARE THE SAME SEGMENTS ARE NOT
C	CONSIDERED TO BE INTERSECTING
C
	REAL MA,MB
	LOGICAL FLAG,VERT,A
C
	VERT=.FALSE.
	FLAG=.FALSE.
C
	IF (AX1.EQ.BX1.AND.AY1.EQ.BY1) RETURN	!SAME START POINT
	IF (AX2.EQ.BX2.AND.AY2.EQ.BY2) THEN	!SAME END POINT
		FLAG=.TRUE.
		X=AX2
		Y=AY2
		RETURN
	ENDIF
C
	DENOM=AX1-AX2
	IF (DENOM.EQ.0.0) THEN		!VERTICAL LINE
		MA=1.E10
		VERT=.TRUE.
	ELSE
		MA=(AY1-AY2)/DENOM	!SLOPE OF SEGMENT A
	ENDIF
	DENOM=BX1-BX2
	IF (DENOM.EQ.0.0) THEN		!VERTICAL LINE
		MB=1.E10
		VERT=.TRUE.
	ELSE
		MB=(BY1-BY2)/DENOM	!SLOPE OF SEGMENT B
	ENDIF
	IF (MA.EQ.MB) RETURN		!PARALELL
	CA=AY1-MA*AX1
	CB=BY1-MB*BX1
	IF (VERT) THEN
		IF (MA.EQ.1.E10) THEN
			X=AX1
			Y=X*MB+CB
		ENDIF
		IF (MB.EQ.1.E10) THEN
			X=BX1
			Y=X*MA+CA
		ENDIF
	ELSE
		X=(CA-CB)/(MB-MA)
		Y=MA*X+CA
	ENDIF
C	INTERSECTION OF LINES THROUGH POINTS IS AT X,Y
	DA=(AX1-AX2)**2+(AY1-AY2)**2
	DA1=(AX1-X)**2+(AY1-Y)**2
	IF (DA1.GT.DA) RETURN
		DA2=(AX2-X)**2+(AY2-Y)**2
		IF (DA2.GT.DA) RETURN
			DB=(BX1-BX2)**2+(BY1-BY2)**2
			DB1=(BX1-X)**2+(BY1-Y)**2
			IF (DB1.GT.DB) RETURN
				DB2=(BX2-X)**2+(BY2-Y)**2
				IF (DB2.GT.DB) RETURN
					IF (MA.GT.MB) THEN
						A=.TRUE.
					ELSE
						A=.FALSE.
					ENDIF
					FLAG=.TRUE.
					RETURN
	END
