C
C *** LAST REVISED ON  4-JAN-1994 10:22:53.84
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.MASTER]PICHRT.FOR
C
	SUBROUTINE PICHRT(X0,Y0,RAD,D,IFLAG,AST,N,VALS,ISH,IWT,
     $		LABELS,NCH,CS,ALEG,T,NT,TCS,DIS,ABC,ICOL)
C
C	ROUTINE TO PLOT A PIE CHART WITH SHADED WEDGES, DESCRIPTIVE
C	LEGENDS AND EXPLODED SLICES.
C
C	WRITTEN:  DGL  AUG 1987
C
C	X0,Y0	(R) CENTER OF PIE CHART
C	RAD	(R) RADIUS OF PIE CHART (RAD>0)
C	D	(R) EXPLODE DISTANCE (D>0)
C	IFLAG	(R) PLOTTING FLAG
C			< 0 DON'T CLOSE PLOT PACKAGE
C			> 0 CLOSE PLOT PACKAGE
C		MAG	> 10000 INIT PLOT PACKAGE
C	(ONE'S DIGIT)   = 1 DON'T USE COLORS
C		        = 2 USE COLORS
C	(HUNDRED'S)	= SCREEN GRAPHICS DEVICE (SEE FRAME)
C	AST	(R) STARTING ANGLE
C	N	(I) NUMBER OF WEDGES
C	VALS	(R) ANGULAR PERCENT OF PIE CHART FOR EACH WEDGE
C		     DIMENSIONED VALS(N), WEDGES INCREMENT CCW
C		     IF VALS(I)<0 THEN WEDGE IS EXPLODED OUT FROM CENTER
C		     D DISTANCE
C	ISH	(R) SHADE OPTION FOR EACH WEDGE DIMENSIONED ISH(N)
C			VALUE OF ISH   SHADE PATTERN
C			    0		 NO SHADING (OUTLINE ONLY)
C			    1		 -45 DEG SOLID LINES
C			    2		 HORIZONTAL SOLID LINES
C			    3		 +45 DEG SOLID LINES
C			    4		 VERTICAL SOLID LINES
C			    5		 -45 DEG DOTTED LINES
C			    6		 HORIZONTAL DOTTED LINES
C			    7		 +45 DEG DOTTED LINES
C			    8		 VERTICAL DOTTED LINES
C			    9		 +/- 45 DEG DOTTED LINES
C			   10		 HORIZONTAL/VERTICAL DOTTED LINES
C			   11		 +/- 45 DEG SOLID LINES
C			   12		 HORIZONTAL/VERTICAL SOLID LINES
C	IWT	(I) PEN WIDTH FOR WEDGE OUTLINES (SEE NEW PEN)
C	LABELS	(C) LABELS FOR WEDGES DIMENSIONED LABELS(N)
C	NCH	(I) MAXIMUM NUMBER OF CHARACTERS IN LABELS
C	ALEG	(R) SIZE OF LEGEND BOX 
C		    < 0 LEGENDS LOCATED BELOW PIE CHART
C		    = 0 NO LEGEND (LABELS IGNORED)
C		    > 0 LEGENDS LOCATED AROUND PIE CHART
C	(MAG)	    > 98 LEGEND WITH NO BOXED AREA
C	CS	(R) LEGEND CHARACTER SIZE
C	T	(C) TITLE
C	NT	(I) CHARACTERS IN TITLE
C	TCS	(R) TITLE SIZE
C		    IF TCS <0 THEN INPUT POSITIONS IN ABC USED
C	ABC	(R) LOCATION OF LOWER-LEFT CORNER OF EACH LEGEND
C		    LINE (USED IF TCS<0)
C			ABC(1)=X POSITION LEGEND LABEL 1
C			ABC(2)=Y POSITION LEGEND LABEL 1
C			ABC(3)=X POSITION LEGEND LABEL 2
C			ABC(4)=Y POSITION LEGEND LABEL 2
C			 ...
C	DIS	(R) SHADING LINE DISTANCE
C	ICOL	(I) COLOR ARRAY
C		    ICOL(1) = TITLE COLOR (RETURN)
C		    ICOL(2) = LEGEND LABEL COLOR
C		    ICOL(3) = COLOR OF WEDGE 1
C		     ...          ...        2
C
	DIMENSION VALS(*),ISH(*),IWT(*),ICOL(*),ABC(*)
	CHARACTER*(*) T,LABELS(*)
C
C	CIRCLE RESOLUTION AND WORK SPACE
C
	PARAMETER (RES=0.1)	! CIRCLE RESOLUTION
	PARAMETER (NWORK=1000)	! WORK SPACE
	DIMENSION W(NWORK)
C
	LOGICAL REPEAT
	SAVE REPEAT
	DATA DTR/0.0174533/,REPEAT/.FALSE./
C
C	INTIALIZE ROUTINE AND PLOT PACKAGE IF REQUIRED
C
	IF (IFLAG.EQ.0) THEN
		IF (REPEAT) CALL PLOTND	!CLOSE PLOTTER
		REPEAT=.FALSE.
		RETURN
	ENDIF
C
C	INTIALIZE PLOT PACKAGE
C
	JF=IABS(IFLAG)
	IF (.NOT.REPEAT.AND.JF.LT.10000) THEN
		ILU=JF/100			!GRAPHICS DEVICE CODE
		CALL FRAME(3,ILU,1.5,1.0,1.)	!INTIALIZE
	ELSE
		CALL CTERM(-1)			!PUT TERMINAL IN PLOT MODE
	ENDIF
	JF=MOD(IFLAG,10)			!COLOR FLAG
C
C	MUST HAVE POSITIVE RADIUS
C
	IF (RAD.LE.0.0.OR.N.LT.1) GOTO 200
	SCALE=0.0
	DO 10 I=1,N
		SCALE=SCALE+ABS(VALS(I))
10	CONTINUE
	IF (SCALE.EQ.0.0) GOTO 200
	SCALE=360.0/SCALE
C
	ANG=AST
	DO 100 I=1,N
		IF (VALS(I).EQ.0.0) GOTO 100
		ANG1=ANG+ABS(VALS(I))*SCALE
		X1=X0
		Y1=Y0
		IF (VALS(I).LT.0.0) THEN
			X1=X0+COS((ANG+ANG1)*DTR/2.)*D
			Y1=Y0+SIN((ANG+ANG1)*DTR/2.)*D
		ENDIF
		IF (JF.EQ.2) CALL PLOT(FLOAT(ICOL(I+2)),0.,0)
C
C	DO OUTLINE
C
		AN=0.0
		IL=0
		CALL CSHADE(X1,Y1,RAD,ANG,ANG1,RES,1,DIS,
     $			AN,W,IL,IWT(I)*10)
C
C	FILL REGION WITH DESIRED FILL PATTERN
C
		IF (ISH(I).EQ.0) GOTO 90
		AN=45.0*(MOD(ISH(I)-1,4)-1)
		IL=10
		IF (ISH(I).GT.4.AND.ISH(I).LT.11) IL=11
		CALL CSHADE(X1,Y1,RAD,ANG,ANG1,RES,2,DIS,
     $			AN,W,IL,-1)
		IF (ISH(I).GT.8) THEN
			AN=AN+90.
			IL=11
			IF (ISH(I).GT.10) IL=10
			CALL CSHADE(X1,Y1,RAD,ANG,ANG1,RES,2,DIS,
     $				AN,W,IL,-1)
		ENDIF
90		ANG=ANG1
100	CONTINUE
	IF (IL.EQ.11) CALL NEWPEN(1)
C
C	PLOT LEGEND IF SELECTED
C
	IF (ALEG.EQ.0.0) GOTO 160
	IF (ALEG.LT.0.0.OR.TCS.LT.0.0) THEN
	   Y1=Y0-CS*NCH/2.
	   DO 125 I=1,N
		X1=X0-RAD-CS*1.1*N-0.1
		IF (TCS.LT.0.0) THEN
			X1=ABC(2*I-1)
			Y1=ABC(2*I)
		ENDIF
		IF (ABS(ALEG).LT.99.0) THEN
			W(1)=X1
			W(2)=Y1
			W(3)=X1+ABS(ALEG)
			W(4)=Y1
			W(5)=X1+ABS(ALEG)
			W(6)=Y1+ABS(ALEG)
			W(7)=X1
			W(8)=Y1+ABS(ALEG)
			X1=X1+ABS(ALEG)+0.2
			AN=0.0
			IF(JF.EQ.2)CALL PLOT(FLOAT(ICOL(I+2)),0.,0)
			IL=0
			CALL SHADE(W(1),W(2),4,2,1,DIS,AN,
     $				W(9),IL,0.,1.,0.,1.)
			IF (ISH(I).EQ.0) GOTO 120
			AN=45.0*(MOD(ISH(I)-1,4)-1)
			IL=0
			IF (ISH(I).GT.4.AND.ISH(I).LT.11) IL=1
			CALL SHADE(W(1),W(2),4,2,2,DIS,AN,
     $				W(9),IL,0.,1.,0.,1.)
			IF (ISH(I).GT.8) THEN
			    AN=AN+90.
			    IL=1
			    IF (ISH(I).GT.10) IL=0
			    CALL SHADE(W(1),W(2),4,2,2,DIS,AN,
     $				W(9),IL,0.,1.,0.,1.)
			ENDIF
	 	ENDIF
120		CONTINUE
	        IF (IL.EQ.1) CALL NEWPEN(1)
		IF (JF.EQ.2) CALL PLOT(FLOAT(ICOL(2)),0.,0)
		CALL SYMBOL(X1,Y1,CS,LABELS(I),0.,NCH,-1)
		Y1=Y1+CS*(1.5)
125	   CONTINUE
	ELSE
	  ANG=AST
	  DO 150 I=1,N
	    ANG1=ANG+ABS(VALS(I))*SCALE
C
C	COMPUTE LABEL LENGTH AND TRY TO LOCATE TO LOOK NICE
C
	    W(1)=0.
	    W(2)=0.
	    CALL SYMBOL(W(1),W(2),CS,LABELS(I),0.,NCH,-3)
	    R=RAD+CS+0.1
	    IF (VALS(I).LT.0) R=R+D
	    X1=X0+COS((ANG+ANG1)*DTR/2.)*R
	    Y1=Y0+SIN((ANG+ANG1)*DTR/2.)*R
	    IF (X1.LT.X0) X1=X1-W(1)
	    IF (VALS(I).EQ.0.0) GOTO 140
	    IF (ABS(ALEG).LT.99.0) THEN
	        IF (X1.LT.X0) X1=X1-ABS(ALEG)
	        IF (Y1.LT.Y0) Y1=Y1-ABS(ALEG)
		W(1)=X1
		W(2)=Y1
		W(3)=X1+ABS(ALEG)
		W(4)=Y1
		W(5)=X1+ABS(ALEG)
		W(6)=Y1+ABS(ALEG)
		W(7)=X1
		W(8)=Y1+ABS(ALEG)
		X1=X1+ABS(ALEG)+0.2
		AN=0.0
		IF(JF.EQ.2)CALL PLOT(FLOAT(ICOL(I+2)),0.,0)
		CALL SHADE(W(1),W(2),4,2,1,DIS,AN,
     $			W(9),0,0.,1.,0.,1.)
		IF (ISH(I).EQ.0) GOTO 140
		AN=45.0*(MOD(ISH(I)-1,4)-1)
		IL=0
		IF (ISH(I).GT.4.AND.ISH(I).LT.11) IL=1
		CALL SHADE(W(1),W(2),4,2,2,DIS,AN,
     $			W(9),IL,0.,1.,0.,1.)
		IF (ISH(I).GT.8) THEN
		    AN=AN+90.
		    IL=1
		    IF (ISH(I).GT.10) IL=0
		    CALL SHADE(W(1),W(2),4,2,2,DIS,AN,
     $			W(9),IL,0.,1.,0.,1.)
		ENDIF
		   ENDIF
140	    CONTINUE
	    IF (IL.EQ.1) CALL NEWPEN(1)
	    IF (JF.EQ.2) CALL PLOT(FLOAT(ICOL(2)),0.,0)
	    CALL SYMBOL(X1,Y1,CS,LABELS(I),0.,NCH,-1)
	    Y1=Y1+CS*(1.5)
	    ANG=ANG1
150	  CONTINUE
	ENDIF
C
C	ADD TITLE IF SELECTED
C
160	CONTINUE
	IF (JF.EQ.2) CALL PLOT(FLOAT(ICOL(1)),0.,0)
	IF (NT.GT.0) THEN
		X1=0.
		Y1=0.
		CALL SYMBOL(X1,Y1,ABS(TCS),T,0.,NT,-3)
		X1=X0-X1/2.
		Y1=Y0+RAD+CS+0.20
		IF (ABS(ALEG).LT.98.0) Y1=Y1+ABS(ALEG)
		CALL SYMBOL(X1,Y1,ABS(TCS),T,0.,NT,-1)
	ENDIF
C
C	FINISH UP
C
200	CALL PLOT(0.,0.,3)			!PEN UP
	IF (IFLAG.GT.0) THEN
		CALL CTERM(2)			!CLEAR TERMINAL
		CALL PLOTND			!CLOSE PLOT OUTPUT
		REPEAT=.FALSE.
	ENDIF
	IF (IFLAG.LT.0) THEN
		REPEAT=.TRUE.
		CALL CTERM(1)			!PUT TERMINAL IN TEXT MODE
	ENDIF
	RETURN
	END
