C
C *** LAST REVISED ON  4-JAN-1994 10:24:21.15
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.MASTER]T3DH.FOR
C
	SUBROUTINE T3DH(A,INX,INY,NX,NY,PSI,PHI,THETA,
     $		DV,XH,YH,ZH,IFLAG,IAXIS,
     $		XT,NXT,XASTART,XAEND,TX,TSX,PGX,FSX,
     $		YT,NYT,YASTART,YAEND,TY,TSY,PGY,FSY,
     $		ZT,NZT,TZ,TSZ,PGZ,FSZ,AMININ,AMAXIN,ICOL)
C
C	CREATED BY D. LONG     FEB, 1986	AT JPL
C
C	ROUTINE TO PLOT DATA IN A TRIANGULAR 3-D MESH FORM WITH HIDDEN LINE
C	REMOVAL USING THE INIT3DH ROUTINES.
C
C	A	(R) ARRAY A(INX,INY) CONTAINING VERTICAL HEIGHT DATA
C	INX,INY (I) DIMENSION OF A ARRAY
C	NX,NY	(I) INDICATING SIZE OF A ARRAY TO PLOT
C	PSI,PHI,THETA (R) ANGLES (IN DEGREES) OF INIT3DH
C	DV	(R) PERSPECTIVE FACTOR OF INIT3DH (9999=NO PERSPECTIVE)
C		    DV < 0 DO NOT INITIALIZE INIT3DH
C	XH,YH,ZH (R) LENGTH OF EACH AXIS (INCHES)
C	IFLAG	(I) PLOT FLAG
C		>1000	REPEAT PLOTTING BUT DO NOT INTIALIZE PLOTTER
C		< 0	REPEAT PLOTTING (DON'T CLOSE PLOTTER OUTPUT)
C		= 0	CLOSE PLOTTER OUTPUT--DO NOT PRODUCE PLOT
C		> 0	SINGLE PLOT OUTPUT ONLY (PLOTTER OUTPUT CLOSED)
C 	(ONE'S DIGIT) = 2 USE RAM TEK COLOR CONTROL ARRAY
C		      = 1 DO NOT USE RAM TEK COLOR ARRAY
C	(TEN'S DIGIT) = 0 NO HIDDEN LINE REMOVAL FOR AXIS
C		      = 1 HIDDEN LINE REMOVAL OF AXIS
C		      = 2 NO HIDDEN LINES AT ALL (SKETCH USED)
C		      = 3 NO HIDDEN LINES AT ALL (SKETCH NOT USED)
C 	(HUNDRED'S)   = 0 ASK WHICH SCREEN DEVICE TO USE
C		      <>0 SCREEN DEVICE CODE NUMBER
C 	IAXIS	(I) AXIS OPTION FLAG
C			= 0	DO NOT PLOT AXIS--FOLLOWING VARIABLES NOT ACCESSED
C			< 0	PLOT AXIS, USE INPUT Z AXIS SCALE
C			> 0	PLOT AXIS, USE COMPUTED Z AXIS SCALE
C 	(ONE'S DIGIT)	= 1	PLOT AXIS, Y AXIS SCALE--VARIABLES ACCESSED
C			= 2	PLOT AXIS, AUTO SCALE Y AXIS--VARIABLES ACCESSED
C 	XT,YT,ZT	(B) STRINGS FOR AXIS TITLES
C 	NXT,NYT,NZT	(I)  LENGTH OF AXIS TITLES
C			     IF ZERO THEN THAT AXIS NOT PLOTTED
C 	XASTART,YASTART	(R) AXIS START VALUES
C 	XAEND,YAEND	(R) AXIS END VALUES
C FOLLOWING ONLY ACCESSED IF IAXIS<>0
C	TX,TY,TZ	(R) NUMBER OF TICK MARKS (SEE AXIS3DH)
C	TSX,TSY,TSZ	(R) SIZE OF TITLE AND NUMBERS OF AXIS
C			  IF LESS THAN ZERO DO NOT AUTO-SCALE BY (x10^POWER)
C	PGX,PGY,PGZ	(R) ROTATION OF TEXT AND TICKS AROUND AXIS (DEG)
C	FSX,FSY,FSZ	(R) NUMBER FORMAT OF AXISES (SEE AXIS3DH)
C 	AMININ,AMAXIN 	(R) YAXIS SCALING FACTORS (ONLY NEEDED IF IAXIS < 0)
C	ICOL		(I) COLOR INDEX TABLE (ACCESSED IF 1'S DIGIT OF IFLAG=2
C				ICOL(1) AXIS COLOR
C				ICOL(2) SURFACE COLOR
C			    NOTE: WHEN BOTH AXIS AND SURFACE USE SKETCH
C			    BOTH ARE PLOTTED USING SURFACE COLOR
C
	DIMENSION A(INX,INY),PAS(2),ICOL(2)
	LOGICAL REPEAT,HIDDEN
	SAVE REPEAT
	CHARACTER*(*) XT,YT,ZT
C
	DIMENSION XX(4),YY(4),ZZ(4)
C
	PARAMETER (IWRKSZE=100000)
	COMMON /GO/ISIZE,WORK(IWRKSZE)
	SAVE /GO/
	DATA REPEAT/.FALSE./
C
	IF (ISIZE.LT.IWRKSZE) ISIZE=IWRKSZE	! INCREASE WORKSPACE IF NEEDED
C
	IF (IFLAG.EQ.0) THEN
		IF (REPEAT) CALL PLOTND	!CLOSE PLOTTER
		REPEAT=.FALSE.
		RETURN
	ENDIF
C
	IF (IAXIS.LT.0) THEN
		AMAX=AMAXIN
		AMIN=AMININ
	ELSE
		AMAX=A(1,1)
		AMIN=A(1,1)
		DO 16 IY=1,NY			!DETERMINE MAX,MIN ARRAY VALUES
			DO 16 IX=1,NX
				AMAX=AMAX1(AMAX,A(IX,IY))
				AMIN=AMIN1(AMIN,A(IX,IY))
16		CONTINUE
	ENDIF
C
	XLEN=ABS(XH)
	YLEN=ABS(YH)
	ZLEN=ABS(ZH)
	IF (MOD(IABS(IAXIS),10).EQ.2) THEN
		PAS(1)=AMAX
		PAS(2)=AMIN
		CALL SCALE(PAS,ZLEN,2,1,1,AMIN,DAA)
		AMAX=ZLEN*DAA+AMIN
	ENDIF
C
C	INTIALIZE PLOT PACKAGE
C
	JF=IABS(IFLAG)
	IF (.NOT.REPEAT.AND.JF.LT.10000) THEN
		ILU=MOD(JF,10000)/100
		CALL FRAME(3,ILU,1.5,0.65,1.)		!INTIALIZE
	ELSE
		CALL CTERM(-1)				!PUT TERMINAL PLOT MODE
	ENDIF
C
	HIDDEN=.TRUE.
	IOPT=MOD(JF,100)/10
	IF (IOPT.EQ.3) THEN
		IOPT=0
		HIDDEN=.FALSE.
	ENDIF
	JF=MOD(JF,10)
C
C	INITIALIZE 3DH PACKAGE
C
      	MNE=3			! MAX NUMBER OF EDGES
      	MNH=0			! NO HOLES
	ICORE=(25+5*MNE+4*MNH)*NX*NY
	IF (IAXIS.NE.0) ICORE=ICORE+10000	! ESTIMATED AXISES SPACE
	IF (ICORE.GT.ISIZE) THEN
		CALL CTERM(1)
		WRITE (*,3020)
3020		FORMAT(' *** WARNING: COMMON BLOCK /GO/ MAY BE TOO SMALL')
		CALL CTERM(-1)
	ENDIF
	SF=1.0			! SCALE FACTOR
	IF (IOPT.EQ.2) SF=-1.0	! NO HIDDEN LINE REMOVAL
	IF (DV.GT.0.) CALL INIT3DH(0.,0.,0.,PSI,PHI,THETA,SF,DV,MNE,MNH)
C
	IF (IAXIS.NE.0) THEN		!PLOT AXIS LABELS
		IF (JF.EQ.2) CALL PLOT(FLOAT(ICOL(1)),0.,0) !RAM TEK COLOR
		IF (NXT.GT.0) THEN 	!PLOT X AXIS
			CALL AXIS3DH(0.,0.,0.,0.,0.,PGX,XT,
     $				NXT,XLEN,XASTART,XAEND,
     $				TX,TSX,FSX,IOPT)
		ENDIF
		IF (NYT.GT.0) THEN 	!PLOT Y AXIS
			CALL AXIS3DH(0.,0.,0.,0.,90.,PGY,YT,
     $				NYT,YLEN,YASTART,YAEND,
     $				TY,TSY,FSY,IOPT)
		ENDIF
		IF (NZT.GT.0) THEN 	!PLOT Z AXIS
			CALL AXIS3DH(0.,0.,0.,90.,0.,PGZ,ZT,
     $				NZT,-ZLEN,AMIN,AMAX,
     $				TZ,TSZ,FSZ,IOPT)
		ENDIF
	ENDIF
	IF (JF.EQ.2) CALL PLOT(FLOAT(ICOL(2)),0.,0) !RAM TEK COLOR
C
C	BEGIN SURFACE PLOTTING
C
	XXX=NX
	DX=XLEN/IABS(NX)
	DY=YLEN/IABS(NY)
	DZ=1.0
	IF (AMAX-AMIN.NE.0.0) DZ=ZLEN/(AMAX-AMIN)
C
	DO 50 IY=1,IABS(NY)-1	! FOR EACH Y CELL
		Y1=(IY-1)*DY
		Y2=IY*DY
		DO 50 IX=1,IABS(NX)-1	! FOR EACH X CELL
			X1=(IX-1)*DX
			X2=IX*DX
C
			XX(1)=X1
			XX(2)=X2
			XX(3)=X2
			XX(4)=X1
			YY(1)=Y1
			YY(2)=Y1
			YY(3)=Y2
			YY(4)=Y1
			ZZ(1)=(A(IX  ,IY)   - AMIN)*DZ
			ZZ(2)=(A(IX+1,IY)   - AMIN)*DZ
			ZZ(3)=(A(IX+1,IY+1) - AMIN)*DZ
			ZZ(4)=ZZ(1)
			NC=4
			IERR=0
			IF (HIDDEN) THEN
				CALL SKETCH(XX,YY,ZZ,NC,IERR)
			ELSE
				IERR=3
				DO 20 JF=1,NC
				  CALL PLT3DH(XX(JF),YY(JF),ZZ(JF),IERR)
				  IERR=2
20				CONTINUE
			ENDIF
			IF (IERR.LT.0) THEN
				CALL CTERM(1)
		WRITE(*,3010) IERR
3010		FORMAT(' *** WARNING: SKETCH ERROR HAS OCCURED',I3)
				CALL CTERM(-1)
			ENDIF
C
			XX(1)=X1
			XX(2)=X1
			XX(3)=X2
			XX(4)=X1
			YY(1)=Y1
			YY(2)=Y2
			YY(3)=Y2
			YY(4)=Y1
			ZZ(1)=(A(IX  ,IY)   - AMIN)*DZ
			ZZ(2)=(A(IX  ,IY+1)   - AMIN)*DZ
			ZZ(3)=(A(IX+1,IY+1) - AMIN)*DZ
			ZZ(4)=ZZ(1)
			NC=4
			IERR=0
			IF (IY.EQ.IABS(NY)-1.AND.IX.EQ.IABS(NX)-1) IERR=1
			IF (HIDDEN) THEN
				CALL SKETCH(XX,YY,ZZ,NC,IERR)
			ELSE
				IERR=3
				DO 25 JF=1,NC
				  CALL PLT3DH(XX(JF),YY(JF),ZZ(JF),IERR)
				  IERR=2
25				CONTINUE
			ENDIF
			IF (IERR.LT.0) THEN
				CALL CTERM(1)
		WRITE (*,3200) IERR
3200		FORMAT(' *** WARNING: SKETCH ERROR HAS OCCURED',I3)
				CALL CTERM(-1)
			ENDIF
 50	CONTINUE
C
C	FINISH ROUTINE
C
	IF (.NOT.HIDDEN) CALL PLT3DH(XX(1),YY(1),ZZ(1),3)	!PEN UP
	CALL PLOT(0.,0.,3)			!PEN UP
	IF (IFLAG.GT.0) THEN
		CALL CTERM(2)			!CLEAR TERMINAL
		CALL PLOTND			!CLOSE PLOT OUTPUT
		REPEAT=.FALSE.
	ENDIF
	IF (IFLAG.LT.0) THEN
		REPEAT=.TRUE.
		CALL CTERM(1)			!PUT TERMINAL IN TEXT MODE
	ENDIF
	RETURN
	END
