C
C *** LAST REVISED ON  8-DEC-1993 07:03:25.89
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.MASTER]MLIB.FOR
C
	SUBROUTINE VXPT3D(X,Y,AVAL,IX,IZ,NX)
C
C	CREATED BY DAVID LONG    AUG, 1982	AT JPL
C	SUBPROGRAM OF VAX3D
C
C	ROUTINE TO DETERMINE X,Y VALUE OF A POINT ON 3-D SURFACE
C	FOR VAX3DX
C
	COMMON /LOCATE/ XSCALE,YSCALE,ZSCALE,AMIN,ALPH,BET
	SAVE /LOCATE/
	X=XSCALE*FLOAT(IX-1)*COS(ALPH)+FLOAT(IZ-1)*COS(BET)*ZSCALE
	Y=YSCALE*(AVAL-AMIN)+FLOAT(NX-IX+1)*SIN(ALPH)*XSCALE+
     $		FLOAT(IZ-1)*SIN(BET)*ZSCALE
	RETURN
	END
