C
C
	SUBROUTINE MATMUL4(R,A,B)
C
C	CREATED: DGL 1-AUG-1984
C
C	THIS SUBROUTINE MULTIPLIES TWO 4X4 MATRICES A X B = R
C	A CAN BE C (IN PLACE)
C
C	R	RESULT MATRIX DIMENSIONED R(4,4)
C	A	INPUT MATRIX DIMENSIONED A(4,4)
C	B	INPUT MATRIX DIMENSIONED B(4,4)
C
	DIMENSION A(4,4),B(4,4),R(4,4),V(4)
	DO 20 J=1,4
		DO 10 K=1,4
			V(K)=0.0
			DO 5 I=1,4
				V(K)=V(K)+A(J,I)*B(I,K)
 5			CONTINUE
10		CONTINUE
		DO 15 K=1,4
			R(J,K)=V(K)
15		CONTINUE
20	CONTINUE
	RETURN
	END
