C
	REAL FUNCTION XVMUL3D(I,X,Y,Z,V,R)
C
C	CREATED: DGL 1-AUG-1984
C
C	RETURNS ONE ELEMENT OF A 3 ELEMENT VECTOR TRANSFORMATION
C
	DIMENSION V(4),R(4)
C
	V(1)=X
	V(2)=Y
	V(3)=Z
	V(4)=0.0
	CALL MTV4(V,R,V)
	XVMUL3D=V(1)
	IF (I.EQ.2) XVMUL3D=V(2)
	IF (I.EQ.3) XVMUL3D=V(3)
	RETURN
	END
