C
C *********************************************************************
C
C THE FOLLOWING ARE ROUTINES USING THE CIA LAND/SEA BIT MAP FILE
C SEE THE COMMENTS IN THE BITMAP AND LNDSEA ROUTINES
C
C *********************************************************************
C
	SUBROUTINE BITMAP(CLONG,XLONG,YLAT,NXPIX,NYPIX,ILAND)
C
C	BITMAP USES THE FILE "LNDSEA1.DAT" TO DRAW AN EARTH LAND MASK WHERE
C	THE LAND SURFACE OF THE EARTH IS DRAWN USING HORIZONTAL LINES
C	ON A RECTANGULAR PROJECTION OF THE EARTH'S SURFACE (SEE LANDMAP).
C	A GRID OF PIXELS IS USED TO LOCATE POINTS WHICH ARE "LOOKED UP"
C	IN LNDSEA1.DAT (WHICH IS INTERPOLATED) TO DETERMINE IF EACH PIXEL
C	IS LAND/SEA.  USING HORIZONTAL SCANS, A PLOT LINE IS GENERATED OF
C	THE LAND/SEA AREA WHICH IS OUTPUT WHEN THE TYPE CHANGES.  NOTE
C	FOR HIGH DENSITY PLOTS THIS OPERATION IS VERY SLOW DUE TO THE HIGH
C	NUMBER OF FILE READS OF LNDSEA1.DAT REQUIRED.
C
C	INPUTS:
C		CLONG	(R)	LEFT SIDE LONGITUDE OF MAP (DEGREES -180,180)
C		XLONG	(R)	LENGTH OF LONGITUDE AXIS (INCHES)
C		YLAT	(R)	LENGTH OF LATTITUDE AXIS (INCHES)
C		NXPIX	(I)	NUMBER OF PIXELS IN X DIRECTION
C		NYPIX	(I)	NUMBER OF PIXELS IN Y DIRECTION
C		ILAND	(I)	LAND/SEA FLAG
C				 = 0 PLOT LAND
C				 = 1 PLOT SEA
C	OUPUTS: (NONE)
C	CALLS:
C		LNDSEA
C		PLOT
C
	LOGICAL PENUP,LAND,OPTION
C
	XPIX=NXPIX
	YPIX=NYPIX
	CCC=XLONG*(CLONG+180.)/360.
	OPTION=.TRUE.
	IF (ILAND.NE.0) OPTION=.FALSE.
C
	DO 100 ILINE=1,NYPIX
		LINE=NYPIX-ILINE+1
		RLAT=(90.-FLOAT(LINE-1)/YPIX*180.)
		PENUP=.TRUE.
		Y=(YPIX-FLOAT(LINE-1))*YLAT/YPIX
		X0=0.
		Y0=Y
		DO 50 I=1,NXPIX
			RLON=(FLOAT(I-1)/XPIX)*360.-180.	
			X=(FLOAT(I-1)*XLONG/XPIX)
			IF(RLON.LT.0.) RLON=RLON+360.
			IMAP=LNDSEA(RLAT,RLON)
			LAND=.TRUE.
			IF (IMAP.EQ.0) LAND=.FALSE.
			IF (((.NOT.LAND).AND.OPTION).OR.
     $			    ((.NOT.OPTION).AND.LAND)) THEN
				IF (PENUP) THEN
					X0=X
					Y0=Y
					PENUP=.FALSE.
				ENDIF
			ELSE
				IF (.NOT.PENUP) THEN
					X1=X0-CCC
					Y1=Y0
					X2=X-CCC
					Y2=Y
					IF (X1.LE.0.) THEN
					    IF (X2.LT.0.) THEN
						X1=X1+XLONG
						X2=X2+XLONG
						CALL PLOT(X1,Y1,3)
						CALL PLOT(X2,Y2,2)
					    ELSE
						X1=X1+XLONG
						CALL PLOT(0.,Y1,3)
						CALL PLOT(X2,Y2,2)
						CALL PLOT(X1,Y1,3)
						CALL PLOT(XLONG,Y2,2)
					    ENDIF
					ELSE
					    IF (X2.GT.0.) THEN
						CALL PLOT(X1,Y1,3)
						CALL PLOT(X2,Y2,2)
					    ELSE
						X2=X2+XLONG
						CALL PLOT(0.,Y2,3)
						CALL PLOT(X1,Y1,2)
						CALL PLOT(X2,Y2,3)
						CALL PLOT(XLONG,Y1,2)
					    ENDIF
					ENDIF
					PENUP=.TRUE.
				ENDIF
			ENDIF
   50		CONTINUE
		IF (.NOT.PENUP) THEN
			CALL PLOT(X0,Y0,3)
			CALL PLOT(X,Y,2)
			PENUP=.TRUE.
		ENDIF
  100	CONTINUE
	RETURN
	END
