C
C *** LAST REVISED ON  8-DEC-1993 08:01:28.38
C *** SOURCE FILE: [LONGD.TEMP]WORLDMAP.FOR
C
	SUBROUTINE DRAWMAP(NAME,IRANK,LU,SLONG,TRANSFORM)
C
C	WRITTEN BY D. LONG MAY 1993  BYU
C
C	DRAWS A *.MAP FILE USING A USER SPECIFIED PROJECTION ROUTINE
C		"TRANSFORM(LATITUDE, LONGITUDE, IPEN)"
C	WHERE IPEN=3 INDICATES "MOVE TO", AND IPEN=2 INDICATES "DRAW TO"
C
C	NAME	CHAR	MAP FILE NAME
C	IRANK	INT	SEGMENT RANK NUMBER TO DRAW (1 TO 15)
C	LU	INT	FILE UNIT NUMBER
C	SLONG	REAL	STARTING LONGITUDE (-180 TO +180)
C	TRANSFORM EXTERNAL
C
	CHARACTER*(*) NAME
	EXTERNAL TRANSFORM
	LOGICAL LAST
	data last/.false./, ir/0/
C
C	OPEN DATA FILE
C
	OPEN(UNIT=LU,FILE=NAME,FORM='UNFORMATTED',STATUS='OLD')
C     $		READONLY)
	ICNT=0
	IEND=0
C
C	READ DATA
C
10	CALL RMFILE(LU,IB1,IB2,IC,ICNT,IEND)
	IF (IEND.LT.0) GOTO 99
C
C	TYPE *,IB1,IB2,IC
	IF (IC.LT.0) THEN
		IR=IB1		! SEGMENT RANK
		IPT=3
		LAST=.FALSE.
		X=SLONG+360.0
	ELSE
		IF (IR.NE.IRANK) GOTO 10
		ALAT=FLOAT(IB1)/3600.0
		ALON=FLOAT(IB2)/3600.0
C		TYPE *,ALON,ALAT
C
		IF (ALON.LT.SLONG) THEN
C
C	LEFT OF DESIRED START LONGITUDE
C
			IF (LAST) THEN
C
C	CLIP INTERSECTION LINE FOR START LONGITUDE
C
				X1=ALON+360.0
				Y1=ALAT
				Y2=Y1-(Y-Y1)*X1/(X-X1)
				CALL TRANSFORM(Y2,X,IPT)
				CALL TRANSFORM(Y2,X1,3)
				CALL TRANSFORM(Y1,X1,2)
				X=X1
				Y=Y1
			ELSE
				X=ALON+360.0
				Y=ALAT
				CALL TRANSFORM(Y,X,IPT)
			ENDIF
			IPT=2
			LAST=.FALSE.
		ELSE
C
C	RIGHT OF DESIRED STARTING LONGITUDE
C
			IF (LAST) THEN
				X=ALON
				Y=ALAT
				CALL TRANSFORM(Y,X,IPT)
			ELSE
C
C	CLIP INTERSECTION LINE
C
				X1=ALON
				Y1=ALAT
				Y2=Y-(Y1-Y)*X/(X1-X)
				CALL TRANSFORM(Y2,X,IPT)
				CALL TRANSFORM(Y2,X1,3)
				IPT=3
				CALL TRANSFORM(Y1,X1,IPT)
				X=X1
				Y=Y1
			ENDIF
			IPT=2
			LAST=.TRUE.
		ENDIF
	ENDIF
C
	GOTO 10
99	CONTINUE
	CALL PLOT(0.,0.,5)
	CLOSE(LU)
	RETURN
	END
