C
C *** LAST REVISED ON  8-FEB-1994 00:05:50.39
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.MAPLIB]POLARMAP.FOR
C ****************************************************************************
C
	SUBROUTINE POLARMAP(X0,Y0,RAD,ANG)
C
C	WRITTEN BY D. LONG JULY 1985  JPL
C
C	DRAWS A LAND-EDGE MAP USING DATA FROM VECTOR LAND MAP FILE
C	THIS ROUTINE USES A POLAR PROJECTION, I.E. LATTITUDE IS ASSUMED
C	TO BE A LINEAR RADIUS FROM THE POLE.
C
C	X0,Y0	REAL	ORIGIN OF THE POLE
C	RAD	REAL	RADIUS OF EQUATOR
C			> 0 NORTHERN HEMISPHERE
C			< 0 SOUTHERN HEMISPHERE
C	ANG	REAL	ANGLE OF PRIME MERIDAN FROM HORIZONTAL (DEG CCW)
C
C	ASSUMES THAT LONGLOC HAS BEEN ASSIGNED THE DIRECTORY OF THE
C	EARTH.DAT FILE STORING THE EARTH LAND-EDGE MAP.  USES FORTRAN
C	FILE UNIT NUMBER 2.
C
	REAL DATIN(10)
	LOGICAL LAST
	INCLUDE 'files.inc'
C
C	OPEN DATA FILE
C
	OPEN(UNIT=2,FILE=EARTH,FORM='FORMATTED',STATUS='OLD')
C     $		READONLY)
C
	DTR=3.1415926/180.0
	AR=ABS(RAD)/90.0
	IPT=3
	LAST=.FALSE.
C
C	READ THE DATA
C
   10	READ(2,1005,END=999) DATIN
 1005	FORMAT(10F8.0)
C
C	CHECK THE STORED DATA COMMAND
C
	DO 20 I=1,10,2
		IF (IFIX(DATIN(I)).EQ.0.AND.
     $		    IFIX(DATIN(I+1)).EQ.0) GOTO 20
		IF (DATIN(I+1).EQ.888.8) THEN
			IPT=3
			GO TO 20
		ENDIF
		IF (ABS(DATIN(I)).GT.180.5.OR.
     $		    ABS(DATIN(I+1)).GT.91.) THEN
			IPT=3
			GO TO 20
		ENDIF
		IF (SIGN(1.,DATIN(I+1)).NE.SIGN(1.,RAD)) THEN
			IPT=3
		ELSE
			ALONG=DATIN(I)
			ALAT=DATIN(I+1)
			R=(90.0-ABS(ALAT))*AR
			A=DTR*(ALONG*SIGN(1.,RAD)+ANG)
			X=COS(A)*R+X0
			Y=SIN(A)*R+Y0
			CALL PLOT(X,Y,IPT)
			IPT=2
		ENDIF
   20	CONTINUE
	GOTO 10
  999	CONTINUE
	CLOSE(2)
C
	RETURN
	END
