C
C
	SUBROUTINE SPRECT1(V,T,P,R)
C
C	CONVERT FROM SPHERICAL TO RECTANGULAR COORDINATES
C	(LATTITUDE-LONGITUDE TYPE SPHERICAL COORDINATES)
C
C	V	(R):	OUTPUT VECTOR (RECTANGULAR COOR.) V(3)
C	T	(R):	THETA INPUT ANGLE (RADIANS)
C	P	(R):	PHI INPUT ANGLE (CONE ANGLE) (RADIANS)
C	R	(R):	RADIUS INPUT
C
	DIMENSION V(3)
	V(1)=R*COS(T)*SIN(P)
	V(2)=R*SIN(T)*SIN(P)
	V(3)=R*COS(P)
	RETURN
	END
