	PROGRAM IMAGMAP
C *** LAST REVISED ON  9-DEC-1993 22:57:03.31
C *** SOURCE FILE: [LONGLIB93.SOURCES.FORTRAN.EXAMPLES]IMAGMAP.FOR
C
	DIMENSION ISTVAL(40000),STVAL(40000)
C
C	OPEN PLOT PACKAGE
C
	CALL FRAME(0,0,1.,1.,1.)
C
C	SET SIZE AND SCALE FACTORS
C
	NSX=100
	NSY=100
	XSIZE=4.0
	YSIZE=4.0
C
C	FILL ARRAY
C
	DO I=1,NSX
		DO J=1,NSY
			N=I+(J-1)*NSX
			STVAL(N)=1.+COS(I*6./FLOAT(NSX))*COS(J*5./FLOAT(NSY))
		END DO
	END DO
C
C	DISPLAY IMAGE MAP TO TEKTRONICS TERMINAL
C
	CALL TERSCL(1,IT,0.,0.,IXT,IYT)
	CALL TERSCL(1,IT,XSIZE,YSIZE,IXT1,IYT1)
	IF (IT.GT.0) THEN		! IF PROPER TEK TERMINAL
	  RJXT=FLOAT(IXT1-IXT)/FLOAT(NSX)
	  RJYT=FLOAT(IYT1-IYT)/FLOAT(NSY)
C
C	SCALE TO THE RANGE -15 TO 0
C
	  DO I=1,NSX*NSY
		ISTVAL(I)=-NINT(STVAL(I)*7.5)
	  END DO
	  CALL CTERM(-1)
	  CALL TEKMAP(ISTVAL,NSX,NSY,NSX,NSY,IXT,IYT,RJXT,RJYT)
	ENDIF
C
C	DISPLAY IMAGE MAP TO RAMTEK DEVICE
C
	CALL RMPIX(0.,0.,IXR,IYR)
	CALL RMPIX(XSIZE,YSIZE,IX1,IY1)
	RJX=(FLOAT(IABS(IX1-IXR))/FLOAT(NSX))
	RJY=(FLOAT(IY1-IYR)/FLOAT(NSY))
	XSC=XSIZE/NSX
	YSC=YSIZE/NSY
C
C	SCALE TO (0..255)
C
	DO I=1,NSX*NSY
		ISTVAL(I)=NINT(STVAL(I)*127)
	END DO
C
C	PLOT TO RAMTEK ONLY IF RAMTEK IS OPEN
C
	ICHAN=IRMCHAN(ID)
	IF (ICHAN.GT.0) THEN
	  CALL RAMMAP(ISTVAL,NSX,NSY,NSX,NSY,IXR,IYR,RJX,RJY)
	ENDIF
C
C	SEND IMAGE MAP TO META FILE
C
c	CALL METMAP(ISTVAL,NSX,NSY,NSX,NSY,0.,0.,XSIZE,YSIZE)
	CALL METMAP2(ISTVAL,NSX,NSY,1,1,NSX,NSY,0.,0.,XSIZE,YSIZE)
	CALL PLOT(4.,4.,-3)
	CALL METMAP2(ISTVAL,NSX,NSY,50,50,100,100,0.,0.,XSIZE,YSIZE)
C
C	NOW AXES PLOT TO ALL DEVICES
C
	CALL PLOT(1.,0.,0)		! SET PLOT COLOR
C
	CALL RECT(0.,0.,XSIZE,YSIZE)
	AF=ANINT(XSIZE)+1.0101
	CALL AXIS3(0.,0.,'X',-1,XSIZE,0.,0.0,XSIZE,AF,0.12,6.2)
	CALL AXIS3(0.,YSIZE,'X',101,XSIZE,0.,0.0,XSIZE,AF,0.12,6.2)
	AF=ANINT(YSIZE)+1.0101
	CALL AXIS3(0.,0.,'Y',1,YSIZE,90.,0.0,YSIZE,AF,0.12,6.2)
	CALL AXIS3(XSIZE,0.,'Y',-101,YSIZE,90.,0.0,YSIZE,AF,0.12,6.2)
	CALL PLOT(0.,0.,5)
C
C	CLEAR SCREENS AND CLOSE PACKAGES
C
	CALL CTERM(2)
	CALL RTERM(2)
	CALL PLOTND
	STOP
	END
